# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1

jobs:
  build:
    parameters:
      coverage:
        type: boolean
        default: false

    docker:
      - image: circleci/python:3.7.4
        environment:
          PIPENV_VENV_IN_PROJECT: true

    working_directory: ~/repo

    steps:
      - checkout

      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Pipfile.lock" }}
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            pipenv install

      - save_cache:
          paths:
            - /usr/local/lib/python3.7/site-packages
          key: v1-dependencies-{{ checksum "Pipfile.lock" }}

      - run:
          name: run tests
          command: |
            pipenv run pytest \
              --junitxml=test-reports/pytest/unitest-junit.xml \
              <<# parameters.coverage >> --cov-report html:test-reports/coverage/ --cov-branch --cov <</ parameters.coverage >> \
              demo

      - store_artifacts:
          path: test-reports
          destination: test-reports

      - store_test_results:
          path: test-reports

workflows:
  version: 2
  test:
    jobs:
      - build

  nightly:
    triggers:
      - schedule:
          cron: '0 0 * * *'
          filters:
            branches:
              only:
                - master
    jobs:
      - build:
          coverage: true